# Generated by Django 3.2.7 on 2022-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
